name: "Test"

on: 
  push:
    branches: [ "main" ]
  pull_request:
    types: ["opened"]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node_version: [20.x, 22.x] # Add the 18.x version
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4.2.0

    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build and run test
      run: npm run test
