name: "Test"

on: 
  push:
    branches: [ "main" ]
  pull_request:
    types: ["opened"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4.2.0
    - name: Setup nodejs 
      uses: setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run test
      run: npm run test
      
    
